### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by PANOSSS1980** [kokospapa8/react-itunes-search#1]
hello from Greece!!!my friend I am begging you could you release it?I have no idea how to make it?pleaseeeeeeeee mannnnnnnnnnnnnn

**Comment by kokospapa8** [comment]
Hi, what do you mean by `releasing` it?
This is just sample app that I am working on but if you want to see them on the site you can 
go "https://kokospapa8.github.io/react-itunes-search" to preview.
