### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [kokospapa8/react-itunes-search#7]
hello from Greece!!!what amazingggggggggggggggggggggggggggg page...the only problem is the few results!!!pleaseeeeeeeeeeee can you make it show unlimited there is way...........I love spanish music so much and I want to find all the songs and the albums!!!check this please!!! 

I found a way to query more records. There is a parameter called offset, which is not mentioned in API documentation.

https://itunes.apple.com/search?term=a&offset=25&limit=25
Enjoy!

https://stackoverflow.com/questions/44177089/itunes-search-api-page-number-for-the-query?fbclid=IwAR1PEmf4CDvEaYJnXa4_ZZ9-BA3L47KGR0klm052sYW3O3AtqYimwuGOgsE

**Comment by kokospapa8** [comment]
#6 I have plan to add infinite loading soon

**Comment by KENPOKASMMA1982** [comment]
woowwwwww...!!!!!!!!!!!!!!pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee can you make it now?pleaseeeeeeeeeeee I am begging youuuuuuuuuuuuuuuuuuuu

**Comment by kokospapa8** [comment]
@KENPOKASMMA1982 
infinite loading added
